
# Loads default set of integrations. Do not remove.
default_config:


homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.50.0/24
        - fd00::/8

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.27.0.0/16

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

